server:
  port: 8082
spring:
  application:
    name: TEST-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://kq:123@eureka-server1:8080/eureka/,http://kq:123@eureka-server2:8081/eureka/

