server:
  port: 8083
spring:
  application:
    name: SERVICE-CONSUMER
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://kq:123@eureka-server1:8080/eureka/,http://kq:123@eureka-server2:8081/eureka/

feign:
  hystrix:
    enabled: true
logging:
  level:
    com:
      john:
        showmecode:
          service:
            UserService: debug

