server:
  port: 8082

spring:
  application:
    namer: Server-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/