server:
  port: 8081

spring:
  application:
    name: register-server
eureka:
  instance:
    hostname: eureka-server2
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://kq:123@eureka-server1:8080/eureka
